# Generated by Django 3.2 on 2021-04-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_no',
        ),
    ]
